#!/usr/bin/env sh

export HEAT_LEDGER_SECRET_PHRASE_ESCAPED=${HEAT_LEDGER_SECRET_PHRASE_ESCAPED:-}
export HEAT_API_KEY=${HEAT_API_KEY:-}

export ARDOR_SECRET_PHRASE_ENCODED=${ARDOR_SECRET_PHRASE_ENCODED:-}

export RPC_PASSWORD=${RPC_PASSWORD:-}