stages:
- build-service
- build-image
#- build_image

before_script:
- touch /tmp/before.txt

after_script:
- touch /tmp/after.txt

build-service:
  image: openjdk:11-jdk
  stage: build-service
  script:
  - ./gradlew clean build singleJar --info
  artifacts:
    paths:
    - service/build/libs/*.jar
    expire_in: 1 month

build-image:
  image: docker:stable
  stage: build-image
  script:
  - docker info
  - cd service
  - ls -aslh
  - docker build --pull --tag loxal/muctool:latest
#  - docker build -t my-docker-image .
#  - docker run my-docker-image /script/to/run/tests