stages:
- build-service
- assemble

before_script:
- touch /tmp/before.txt

after_script:
- touch /tmp/after.txt

build-service:
  image: openjdk:11-jre
  stage: build-service
  script:
  - ./gradlew clean build singleJar --info
  artifacts:
    paths:
    - service/build/libs/*.jar
    expire_in: 1 month

assemble:
  variables:
    PASSWORD: somevalue
  environment:
    name: main
    url: https://muctool.de
  services:
  - docker:dind
  after_script:
  - echo AFTER_SCRIPT $PASSWORD
  - echo AFTER_SCRIPT $SERVICE_SECRET
  - echo AFTER_SCRIPT $TF_VAR_password
  image: docker:stable
  stage: assemble
  script:
  - echo SCRIPT $PASSWORD
  - echo SCRIPT $SERVICE_SECRET
  - echo SCRIPT $TF_VAR_password
  - cd service
  - docker build --pull --tag loxal/muctool:latest .