package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        script {
            name = "Build Service JAR w/ Docker"
            scriptContent = "./gradlew clean build shadowJar --info --no-build-cache"
            dockerImage = "openjdk:13-alpine"
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            dockerPull = true
            dockerRunParameters = "-v /home/minion/.gradle:/root/.gradle"
        }
        script {
            scriptContent = """
                BUILD_COUNTER=%build.counter% 
                sh release.sh '-P password=M0npugis'
                
                sudo su minion
                cd /srv/muctool
                git reset --hard HEAD
                git pull
                sudo chown -R 1000:1000 /srv/muctool
            """.trimIndent()
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            scriptContent = "./gradlew clean build shadowJar --info --no-build-cache -x test"
        }
    }
}
