/*
 * MUCtool Web Toolkit
 *
 * Copyright 2019 Alexander Orlov <alexander.orlov@loxal.net>. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        script {
            name = "Build Service JAR w/ Docker"
            scriptContent = "./gradlew clean build shadowJar --info --no-build-cache"
            dockerImage = "openjdk:13-slim-buster"
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            dockerPull = true
            dockerRunParameters = "-v /home/minion/.gradle:/root/.gradle"
        }
        script {
            scriptContent = """
                BUILD_COUNTER=%build.counter% 
                sh release.sh '-P password=M0npugis'
                
                sudo su minion
                cd /srv/muctool
                git reset --hard HEAD
                git pull
                sudo chown -R 1000:1000 /srv/muctool
            """.trimIndent()
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            dockerImage = "openjdk:13-slim-buster"
            dockerPull = false
        }
        update<ScriptBuildStep>(1) {
            scriptContent = """
                BUILD_COUNTER=%build.counter% 
                #sh release.sh '-P password=M0npugis'
                
                # Refresh MUCtool repository on sky server
                #sudo su minion
                #cd /srv/muctool
                #git reset --hard HEAD
                #git pull
                #sudo chown -R 1000:1000 /srv/muctool
            """.trimIndent()
        }
    }
}
