package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "IssueTracker"
                id = "PROJECT_EXT_5"
                param("secure:password", "")
                param("name", "loxal/muctool")
                param("pattern", """#(\d+)""")
                param("authType", "anonymous")
                param("repository", "https://github.com/loxal/muctool")
                param("type", "GithubIssues")
                param("secure:accessToken", "")
                param("username", "")
            }
        }
    }
}
