apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
---
kind: Pod
apiVersion: v1
metadata:
  name: volume-storage-test
spec:
  containers:
    - name: vst-frontend
      image: busybox
      volumeMounts:
        - mountPath: "/mnt"
          name: storage-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: storage-volume
      persistentVolumeClaim:
        claimName: storage