---
kind: Service
apiVersion: v1
metadata:
  name: teamcity-server
spec:
  selector:
    app: teamcity-server
  ports:
    - port: 8111
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: teamcity-server
  labels:
    app: teamcity-server
spec:
  serviceName: teamcity-server
  selector:
    matchLabels:
      app: teamcity-server
  template:
    metadata:
      name: teamcity-server
      labels:
        app: teamcity-server
    spec:
      volumes:
        - name: local-storage-persistence
          hostPath:
            path: /srv/teamcity-server
      containers:
        - name: teamcity-server
          image: jetbrains/teamcity-server:2019.1.3-linux
          env:
            - name: TEAMCITY_SERVER_MEM_OPTS
              value: "-Xmx2g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"
          volumeMounts:
            - mountPath: /data/teamcity_server/datadir
              name: local-storage-persistence
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: teamcity-agent
  labels:
    app: teamcity-agent
spec:
  selector:
    matchLabels:
      app: teamcity-agent
  template:
    metadata:
      name: teamcity-agent-template
      labels:
        app: teamcity-agent
    spec:
      volumes:
        - name: local-storage-persistence
          hostPath:
            path: /mnt/HC_Volume_3302802/ci/confidential-secrets

        - name: agent-state-merkur-conf
          hostPath:
            path: /srv/teamcity-agent/merkur/conf
        - name: agent-state-merkur-work
          hostPath:
            path: /srv/teamcity-agent/merkur/work
        - name: agent-state-merkur-system
          hostPath:
            path: /srv/teamcity-agent/merkur/system
        - name: agent-state-merkur-temp
          hostPath:
            path: /srv/teamcity-agent/merkur/temp

        - name: agent-state-venus-conf
          hostPath:
            path: /srv/teamcity-agent/venus/conf
        - name: agent-state-venus-work
          hostPath:
            path: /srv/teamcity-agent/venus/work
        - name: agent-state-venus-system
          hostPath:
            path: /srv/teamcity-agent/venus/system

        - name: agent-state-mars-conf
          hostPath:
            path: /srv/teamcity-agent/mars/conf
        - name: agent-state-mars-work
          hostPath:
            path: /srv/teamcity-agent/mars/work
        - name: agent-state-mars-system
          hostPath:
            path: /srv/teamcity-agent/mars/system

      containers:
        - name: teamcity-agent-merkur
          image: jetbrains/teamcity-agent:2019.1.3-linux
          securityContext:
            privileged: true
          env:
            - name: AGENT_NAME
              value: merkur
            - name: DOCKER_IN_DOCKER
              value: start
            - name: SERVER_URL
              value: http://teamcity-server:8111
          volumeMounts:
            - mountPath: /mnt/local-storage-persistence
              name: local-storage-persistence
            #              readOnly: true
            #            - mountPath: /mnt/local-storage-persistence
            #              name: local-storage-persistence
            #              subPath: gradle
            - mountPath: /data/teamcity_agent/conf
              name: agent-state-merkur-conf
            - mountPath: /opt/buildagent/work
              name: agent-state-merkur-work
            - mountPath: /opt/buildagent/system
              name: agent-state-merkur-system
            - mountPath: /opt/buildagent/temp
              name: agent-state-merkur-temp
#        - name: teamcity-agent-venus
#          image: jetbrains/teamcity-agent:2019.1.3-linux
#          securityContext:
#            privileged: true
#          env:
#            - name: AGENT_NAME
#              value: venus
#            - name: DOCKER_IN_DOCKER
#              value: start
#            - name: SERVER_URL
#              value: http://teamcity-server:8111
#          volumeMounts:
#            - mountPath: /mnt/local-storage-persistence
#              name: local-storage-persistence
#              readOnly: true
#            - mountPath: /data/teamcity_agent/conf
#              name: agent-state-venus-conf
#            - mountPath: /opt/buildagent/work
#              name: agent-state-venus-work
#            - mountPath: /opt/buildagent/system
#              name: agent-state-venus-system
#        - name: teamcity-agent-mars
#          image: jetbrains/teamcity-agent:2019.1.3-linux
#          securityContext:
#            privileged: true
#          env:
#            - name: AGENT_NAME
#              value: mars
#            - name: DOCKER_IN_DOCKER
#              value: start
#            - name: SERVER_URL
#              value: http://teamcity-server:8111
#          volumeMounts:
#            - mountPath: /mnt/local-storage-persistence
#              name: local-storage-persistence
#              readOnly: true
#            - mountPath: /data/teamcity_agent/conf
#              name: agent-state-mars-conf
#            - mountPath: /opt/buildagent/work
#              name: agent-state-mars-work
#            - mountPath: /opt/buildagent/system
#              name: agent-state-mars-system
---