---
        {{/*    kubectl create secret docker-registry docker-registry-muctool --docker-server docker.muctool.de --docker-username minion --docker-password $ADMIN_SITE_SECRET -n kube-system*/}}
kind: Secret
apiVersion: v1
metadata:
    name: docker-registry-muctool
data:
    .dockerconfigjson: {{ .Values.app.dockerRegistrySecret }}
type: kubernetes.io/dockerconfigjson
---
        {{/*kubectl create secret tls test-tls --key="tls.key" --cert="tls.crt"*/}}
kind: Secret
apiVersion: v1
metadata:
    name: tls-certificate
type: kubernetes.io/tls
data:
    tls.crt: {{ .Files.Get "fullchain.pem" | b64enc }}
    tls.key: {{ .Files.Get "privkey.pem" | b64enc }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
    name: ingress
    annotations:
            {{/*        nginx.ingress.kubernetes.io/auth-type: basic*/}}
            {{/*        nginx.ingress.kubernetes.io/auth-secret: basic-auth*/}}
            {{/*        nginx.ingress.kubernetes.io/client-body-buffer-size: 100M*/}}
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "*"
        nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range"
        nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS, PUT, DELETE"
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "700" # required for long-lasting crawler calls
spec:
    tls:
        - secretName: tls-certificate
          hosts:
              - muctool.de
              - api.muctool.de
              - cdn.muctool.de
              - es.muctool.de
              - mirror.muctool.de
              - finder.muctool.de
              - logs.muctool.de
              - affiliate.muctool.de
              - loxal.org
              - www.loxal.org
              - epvin.com
              - www.epvin.com
              - erpiv.com
              - www.erpiv.com
              - novitum.de
              - www.novitum.de
              - loxal.net
              - ci.loxal.net
              - sky.loxal.net
              - me.loxal.net
              - blog.loxal.net
              - news.loxal.net
              - bi.loxal.net
    rules:
        - host: muctool.de
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: api.muctool.de
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: cdn.muctool.de
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: es.muctool.de
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: mirror.muctool.de
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: finder.muctool.de
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: logs.muctool.de
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: affiliate.muctool.de
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: loxal.org
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: www.loxal.org
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: epvin.com
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: www.epvin.com
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: erpiv.com
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: www.erpiv.com
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: novitum.de
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: www.novitum.de
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: loxal.net
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: ci.loxal.net
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: sky.loxal.net
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: me.loxal.net
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: blog.loxal.net
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: news.loxal.net
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - host: bi.loxal.net
          http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
        - http:
              paths:
                  - backend:
                        serviceName: router
                        servicePort: 80
                    path: /
---
kind: Service
apiVersion: v1
metadata:
    name: router
spec:
    selector:
        app: router
    ports:
        - port: 80
          name: http
        - port: 443
          name: https
    type: LoadBalancer
    externalIPs:
        - 88.99.37.232
---
kind: Service
apiVersion: v1
metadata:
    name: muctool
spec:
    selector:
        app: muctool
    ports:
        - port: 1180
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: router
    labels:
        app: router
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
    minReadySeconds: 10
    replicas: 1
    selector:
        matchLabels:
            app: router
    template:
        metadata:
            name: router
            labels:
                app: router
        spec:
            imagePullSecrets:
                - name: docker-registry-muctool
            volumes:
                - name: volume-storage-persistence
                  hostPath:
                      path: /mnt/HC_Volume_3302802/mirror
            containers:
                - name: router
                  image: muctool/loadbalancer:latest
                        {{/*                  image: docker.muctool.de/muctool/loadbalancer:latest*/}}
                  volumeMounts:
                      - mountPath: /srv/mirror
                        name: volume-storage-persistence
                        subPath: migrosbank.ch
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: {{ include "muctool.fullname" . }}
    labels:
        app: {{ include "muctool.fullname" . }}
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
    minReadySeconds: 10
    selector:
        matchLabels:
            app: {{ include "muctool.fullname" . }}
    template:
        metadata:
            name: {{ include "muctool.fullname" . }}
            labels:
                app: {{ include "muctool.fullname" . }}
        spec:
            imagePullSecrets:
                - name: docker-registry-muctool
            containers:
                - name: muctool
                  image: docker.muctool.de/muctool/muctool:latest
                  env:
                      - name: MUCTOOL_GITHUB_CLIENT_ID
                        value: {{ .Values.app.githubClientId }}
                      - name: MUCTOOL_GITHUB_CLIENT_SECRET
                        value: {{ .Values.app.githubClientSecret }}
                      - name: SECURITY_USER_PASSWORD
                        value: {{ .Values.app.password }}
                      - name: BUILD_NUMBER
                        value: "{{ .Values.app.meta.buildNumber }}"
                      - name: SCM_HASH
                        value: {{ .Values.app.meta.scmHash }}
---
