---
kind: Secret
apiVersion: v1
metadata:
    name: docker-registry-credentials
data:
    .dockerconfigjson: {{ .Values.app.dockerRegistrySecret }}
type: kubernetes.io/dockerconfigjson
---
        {{/*kubectl create secret tls test-tls --key="tls.key" --cert="tls.crt"*/}}
kind: Secret
apiVersion: v1
metadata:
    name: tls-certificate
type: kubernetes.io/tls
data:
    tls.crt: {{ .Files.Get "cert.pem" | b64enc }}
    tls.key: {{ .Files.Get "privkey.pem" | b64enc }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
    name: ingress
    annotations:
            {{/*        nginx.ingress.kubernetes.io/auth-type: basic*/}}
            {{/*        nginx.ingress.kubernetes.io/auth-secret: basic-auth*/}}
            {{/*        nginx.ingress.kubernetes.io/client-body-buffer-size: 100M*/}}
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "*"
        nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range"
        nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS, PUT, DELETE"
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        nginx.ingress.kubernetes.io/proxy-read-timeout: 600s # required for long-lasting crawler calls
spec:
    tls:
        - secretName: tls-certificate
          hosts:
              - muctool.de
              - api.muctool.de
              - cdn.muctool.de
              - mirror.muctool.de
              - loxal.org
              - www.loxal.org
              - epvin.com
              - www.epvin.com
              - erpiv.com
              - www.erpiv.com
              - novitum.de
              - www.novitum.de
              - finder.muctool.de
              - ci.loxal.net
              - sky.loxal.net
              - me.loxal.net
              - blog.loxal.net
              - news.loxal.net
              - bi.loxal.net
              - es.loxal.net
    rules:
        - host: muctool.de
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: api.muctool.de
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: cdn.muctool.de
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: mirror.muctool.de
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: loxal.org
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: www.loxal.org
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: epvin.com
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: www.epvin.com
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: erpiv.com
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: www.erpiv.com
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: novitum.de
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: www.novitum.de
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: finder.muctool.de
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: ci.loxal.net
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: sky.loxal.net
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: me.loxal.net
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: blog.loxal.net
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: news.loxal.net
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: bi.loxal.net
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - host: es.loxal.net
          http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
        - http:
              paths:
                  - backend:
                        serviceName: muc-router
                        servicePort: 80
                    path: /
---
kind: Service
apiVersion: v1
metadata:
    name: teamcity-agent
spec:
    selector:
        app: teamcity-agent
    ports:
        - port: 9090
---
kind: Service
apiVersion: v1
metadata:
    name: teamcity-server
spec:
    selector:
        app: teamcity-server
    ports:
        - name: main
          port: 8111
        - name: agent
          port: 9090
---
kind: Service
apiVersion: v1
metadata:
    name: muc-router
spec:
    selector:
        app: muc-router
    ports:
        - port: 80
---
kind: Service
apiVersion: v1
metadata:
    name: muctool
spec:
    selector:
        app: muctool
    ports:
        - port: 1180
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: muc-router
    labels:
        app: muc-router
spec:
    selector:
        matchLabels:
            app: muc-router
    template:
        metadata:
            name: muc-router
            labels:
                app: muc-router
        spec:
            imagePullSecrets:
                - name: docker-registry-credentials
            containers:
                - name: muc-router
                  image: loxal/muc-router:latest
                  env:
                      - name: key
                        value: value
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: {{ include "muctool.fullname" . }}
    labels:
        app: muctool
spec:
    selector:
        matchLabels:
            app: muctool
    template:
        metadata:
            name: muctool
            labels:
                app: muctool
        spec:
            containers:
                - name: muctool
                  image: loxal/muctool:latest
                  env:
                      - name: MUCTOOL_GITHUB_CLIENT_ID
                        value: {{ .Values.app.githubClientId }}
                      - name: MUCTOOL_GITHUB_CLIENT_SECRET
                        value: {{ .Values.app.githubClientSecret }}
                      - name: SECURITY_USER_PASSWORD
                        value: {{ .Values.app.password }}
                      - name: BUILD_NUMBER
                        value: "{{ .Values.app.meta.buildNumber }}"
                      - name: SCM_HASH
                        value: {{ .Values.app.meta.scmHash }}
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
    name: teamcity-server
    labels:
        app: teamcity-server
spec:
    serviceName: teamcity-server
    selector:
        matchLabels:
            app: teamcity-server
    template:
        metadata:
            name: teamcity-server
            labels:
                app: teamcity-server
        spec:
            volumes:
                - name: local-storage-persistence
                  hostPath:
                      path: /srv/teamcity-server
            containers:
                - name: teamcity-server
                  image: jetbrains/teamcity-server:2019.1.3-linux
                  env:
                      - name: TEAMCITY_SERVER_MEM_OPTS
                        value: "-Xmx8g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=350m"
                  volumeMounts:
                      - mountPath: /data/teamcity_server/datadir
                        name: local-storage-persistence
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: teamcity-agent
    labels:
        app: teamcity-agent
spec:
    replicas: 1
    selector:
        matchLabels:
            app: teamcity-agent
    template:
        metadata:
            name: teamcity-agent
            labels:
                app: teamcity-agent
        spec:
            containers:
                - name: teamcity-agent
                  image: jetbrains/teamcity-agent:2019.1.3-linux
                  securityContext:
                      privileged: true
                  env:
                      - name: DOCKER_IN_DOCKER
                        value: start
                      - name: SERVER_URL
                        value: "http://teamcity-server:8111"
        {{/*                        value: "https://ci.loxal.net"*/}}
---
kind: Service
apiVersion: v1
metadata:
    name: sis-sitesearch
spec:
    selector:
        app: sis-sitesearch
    ports:
        - port: 8001
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: sis-sitesearch
    labels:
        app: sis-sitesearch
spec:
    replicas: 1
    minReadySeconds: 0
    selector:
        matchLabels:
            app: sis-sitesearch
    template:
        metadata:
            name: sis-sitesearch
            labels:
                app: sis-sitesearch
        spec:
            imagePullSecrets:
                - name: docker-registry-credentials
            containers:
                - name: sis-sitesearch
                  image: muctool/page-finder:latest
                  env:
                      - name: SPRING_PROFILES_ACTIVE
                        value: oss
                      - name: SIS_API_SERVICE_URL
                        value: https://finder.muctool.de
                      - name: SIS_SERVICE_HOST
                        value: finder.muctool.de
                      - name: SERVICE_SECRET
                        value: {{ .Values.app.serviceSecret }}
                      - name: WOO_COMMERCE_CONSUMER_KEY
                        value: none
                      - name: WOO_COMMERCE_CONSUMER_SECRET
                        value: none
                      - name: INVISIBLE_RECAPTCHA_SITE_SECRET
                        value: {{ .Values.app.recaptchaSecret }}
                      - name: ADMIN_SITE_SECRET
                        value: {{ .Values.app.adminSecret }}
                      - name: DEV_SKIP_FLAG
                        value: "false"
                      - name: BUILD_NUMBER
                        value: "{{ .Values.app.meta.buildNumber }}"
                      - name: SCM_HASH
                        value: {{ .Values.app.meta.scmHash }}
---