---
kind: Service
apiVersion: v1
metadata:
    name: page-finder
spec:
    selector:
        app: page-finder
    ports:
        - port: 8001
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: page-finder
    labels:
        app: page-finder
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 2
    replicas: 1
    minReadySeconds: 10
    selector:
        matchLabels:
            app: page-finder
    template:
        metadata:
            name: page-finder
            labels:
                app: page-finder
        spec:
            imagePullSecrets:
                - name: docker-registry-muctool
            containers:
                - name: page-finder
                  image: docker.muctool.de/muctool/page-finder:latest
                  readinessProbe:
                      httpGet:
                          port: 8001
                          path: /sites/563714f1-96c0-4500-b366-4fc7e734fa1d/search?query=schweiz
                      periodSeconds: 10
                      initialDelaySeconds: 10
                  livenessProbe:
                      httpGet:
                          port: 8001
                          path: /sites/563714f1-96c0-4500-b366-4fc7e734fa1d/search?query=schweiz
                      periodSeconds: 60
                  env:
                      - name: ELASTICSEARCH_SERVICE
                        value: http://elasticsearch:9200
                      - name: SIS_API_SERVICE_URL
                        value: https://finder.muctool.de
                      - name: SIS_SERVICE_HOST
                        value: finder.muctool.de
                      - name: SERVICE_SECRET
                        value: {{ .Values.app.serviceSecret }}
                      - name: INVISIBLE_RECAPTCHA_SITE_SECRET
                        value: {{ .Values.app.recaptchaSecret }}
                      - name: ADMIN_SITE_SECRET
                        value: {{ .Values.app.adminSecret }}
                      - name: DEV_SKIP_FLAG
                        value: "{{ .Values.app.devSkipFlag }}"
                      - name: BUILD_NUMBER
                        value: "{{ .Values.app.meta.buildNumber }}"
                      - name: SCM_HASH
                        value: {{ .Values.app.meta.scmHash }}
---
