---
kind: ConfigMap
apiVersion: v1
metadata:
    name: sis-config
data:
    logstash.conf: |
        input {
          beats {
            port => 5044
          }
        }

        filter {
            grok {
                match => {
                    "message" => [
                    "^.+ %{LOGLEVEL:log_level} .+siteId: %{UUID:siteId}"
                    ]
                }
            }

            if [message] =~ "query-fragment:" {
                grok {
                    match => {
                        "message" => "^.+query-fragment: %{WORD:query-fragment} .+autocompletes: %{NUMBER:autocompletes:int} .+autocompleteDurationInMs: %{NUMBER:autocompleteDurationInMs:int}$"
                    }
                    add_tag => [ "autocomplete" ]
                }
            }

            if [message] =~ "query:" {
                grok {
                    match => {
                        "message" => "^.+query: %{WORD:query} .+results: %{NUMBER:results:int} .+searchDurationInMs: %{NUMBER:searchDurationInMs:int}$"
                    }
                    add_tag => [ "search" ]
                }
            }

            if [message] =~ "bodySize" {
                grok {
                    match => {
                        "message" => "^.+bodySize: %{NUMBER:bodySize:int} .+titleSize: %{NUMBER:titleSize:int} .+URL: %{URI:url}$"
                    }
                    add_tag => [ "index" ]
                }
            }

            if [message] =~ " - siteUrl:" {
                grok {
                    match => {
                        "message" => "^.+siteSecret: %{UUID:siteSecret} .+siteUrl: %{URI:siteUrl} .+pageCount: %{NUMBER:pageCount:int} .+email: %{GREEDYDATA:email}$"
                    }
                    add_tag => [ "crawl" ]
                }
            }

            # if log line contains tab character followed by "at", then it is tagged as a stacktrace
            if [message] =~ "\tat" {
                grok {
                    match => ["message", "^(\tat)"]
                    add_tag => [ "stacktrace" ]
                }
            }
        }

        output {
            elasticsearch {
                hosts => [ "elasticsearch" ]
            }
        }
---
kind: Secret
apiVersion: v1
data:
    auth: {{ .Values.app.basicAuthBase64 }}
metadata:
    name: basic-auth
type: Opaque
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
    name: elasticsearch
    labels:
        app: elasticsearch
spec:
    serviceName: elasticsearch
    selector:
        matchLabels:
            app: elasticsearch
    template:
        metadata:
            name: elasticsearch
            labels:
                app: elasticsearch
        spec:
            initContainers:
                - name: set-elasticsearch-requirement
                  image: busybox
                  command: [ "sysctl", "-w", "vm.max_map_count=262144" ]
                  securityContext:
                      privileged: true
                - name: set-persistence-acl
                  image: busybox
                  command: [ "chown", "-R", "1000", "/mnt/tmp" ]
                  securityContext:
                      runAsUser: 0
                  volumeMounts:
                      - mountPath: /mnt/tmp
                        name: volume-storage-persistence
            securityContext:
                fsGroup: 1000
                runAsUser: 1000
                runAsGroup: 1000
                {{/*                runAsNonRoot: true*/}}
            containers:
                - name: elasticsearch
                  image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
                  env:
                      - name: discovery.type
                        value: single-node
                      - name: bootstrap.memory_lock
                        value: "true"
                  volumeMounts:
                      - mountPath: "/usr/share/elasticsearch/data"
                        name: volume-storage-persistence
            volumes:
                - name: volume-storage-persistence
                  hostPath:
                      path: /mnt/HC_Volume_3302802
        {{/*                - name: storage-volume*/}}
        {{/*                  persistentVolumeClaim:*/}}
        {{/*                      claimName: csi-pvc-storage*/}}
---
kind: Service
apiVersion: v1
metadata:
    name: elasticsearch
spec:
    selector:
        app: elasticsearch
    ports:
        - port: 9200
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
    name: logstash
    labels:
        app: logstash
spec:
    selector:
        matchLabels:
            app: logstash
    template:
        metadata:
            name: logstash
            labels:
                app: logstash
        spec:
            volumes:
                - name: config
                  configMap:
                      name: sis-config
            containers:
                - name: logstash
                  image: docker.elastic.co/logstash/logstash:7.4.0
                  volumeMounts:
                      - name: config
                        mountPath: /usr/share/logstash/pipeline/logstash.conf
                        subPath: logstash.conf
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: kibana
    labels:
        app: kibana
spec:
    selector:
        matchLabels:
            app: kibana
    template:
        metadata:
            name: kibana
            labels:
                app: kibana
        spec:
            containers:
                - name: kibana
                  image: docker.elastic.co/kibana/kibana:7.4.0
                  env:
                      - name: XPACK_TELEMETRY_ENABLED
                        value: "false"
                      - name: XPACK_SECURITY_ENABLED
                        value: "true"
                      - name: ELASTICSEARCH_HOSTS
                        value: http://elasticsearch:9200
---
kind: Service
apiVersion: v1
metadata:
    name: kibana
spec:
    selector:
        app: kibana
    ports:
        - port: 5601
---
kind: Service
apiVersion: v1
metadata:
    name: logstash
spec:
    selector:
        app: logstash
    ports:
        - port: 5044
---