apiVersion: v1
kind: Service
metadata:
    name: {{ include "page-finder.fullname" . }}
    labels:
        {{ include "page-finder.labels" . | indent 4 }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
          targetPort: http
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: {{ include "page-finder.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
