version: "3.6"
services:
#  ops-kibana:
#    image: docker.elastic.co/kibana/kibana:6.3.1
#    depends_on:
#      - ops-elasticsearch
#      - ops-elasticsearch-yang
#      - ops-elasticsearch-ying
#      - ops-logstash
#    environment:
#      - xpack.security.enabled=false
#      - xpack.monitoring.report_stats=false
#      - xpack.monitoring.collection.enabled=true
#      - ELASTICSEARCH_URL=http://ops-elasticsearch:9200

  ops-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
      - xpack.security.enabled=false
      - cluster.name=muctool
      - node.name=ops-elasticsearch
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - discovery.zen.ping.unicast.hosts=ops-elasticsearch
#    volumes:
#      - /srv/ops-elasticsearch/data:/usr/share/elasticsearch/data:rw

#  ops-elasticsearch-ying:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
#    environment:
#      - xpack.security.enabled=false
#      - cluster.name=muctool
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
#      - node.name=ops-elasticsearch-ying
#      - discovery.zen.ping.unicast.hosts=ops-elasticsearch,ops-elasticsearch-ying,ops-elasticsearch-yang
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
##    volumes:
##      - /srv/ops-elasticsearch-ying/data:/usr/share/elasticsearch/data:rw
#
#  ops-elasticsearch-yang:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
#    environment:
#      - xpack.security.enabled=false
#      - cluster.name=muctool
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
#      - node.name=ops-elasticsearch-yang
#      - discovery.zen.ping.unicast.hosts=ops-elasticsearch,ops-elasticsearch-ying,ops-elasticsearch-yang
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
##    volumes:
##      - /srv/ops-elasticsearch-yang/data:/usr/share/elasticsearch/data:rw
#
#  ops-logstash:
#    image: docker.elastic.co/logstash/logstash:6.3.1
##    volumes:
##      - /srv/ops-logstash/_data:/usr/share/logstash:rw
#    ports:
#      - 12201:12201/udp